FROM heroku/miniconda

# Install dependencies
ADD environment.yml /tmp/environment.yml
RUN conda env update -f /tmp/environment.yml
RUN echo "source activate smilesbot" > ~/.bashrc
ENV PATH /opt/conda/envs/smilesbot/bin:$PATH

# Add our code
ADD . / /opt/slackbot/
WORKDIR /opt/slackbot

# Run the image as a non-root user
RUN adduser --disabled-password myuser
USER myuser

CMD /opt/conda/envs/smilesbot/bin/python bot.py
